# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksdir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
